name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Devin Apps
      env:
        DEVIN_DEPLOY_TOKEN: ${{ secrets.DEVIN_DEPLOY_TOKEN }}
      run: |
        # Install deployment CLI if needed
        npm install -g @devin/deploy-cli || echo "CLI already installed"
        
        # Deploy using Devin's deployment service
        devin-deploy --app-id todo-app-lzzpuzmq --build-dir ./dist --token $DEVIN_DEPLOY_TOKEN
